version: '3'

services: 
  db:
    image: postgres:9.6.6
    env_file:
      - ./.env
    volumes:
    - ./pg_init/init.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    env_file:
        - ./.env
    build:
      context: ./address-validator
      dockerfile: "./Dockerfile"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db